FPS = 60

TILE_SIZE = 25
X_TILES = 21
Y_TILES = 30
WIDTH = TILE_SIZE * X_TILES
HEIGHT = TILE_SIZE * Y_TILES

PLAYER_SPAWN_X = 10
PLAYER_SPAWN_Y = 28

TRUCK_PROBABILITY = 0.3
LARGE_LOG_PROBABILITY = 0.2
MEDIUM_LOG_PROBABILITY = 0.3

SPAWN_TIME_LIMIT = 1